# Reproducible Research: Peer Assessment 1
========================================================

## Loading and preprocessing the data
```{r}
activity <- read.csv("~/Desktop/Working Directory/activity.csv")
```

## What is mean total number of steps taken per day?
```{r}
Steps.taken <- aggregate(steps ~ date, data = activity, FUN = sum)
barplot(Steps.taken$steps, names.arg = Steps.taken$date, xlab = "date", ylab = "steps")
mean(Steps.taken$steps)
median(Steps.taken$steps)
```


## What is the average daily activity pattern?
```{r}
average.activity <- aggregate(steps ~ interval, data = activity, FUN = mean)
plot(average.activity, type = "l")
average.activity$interval[which.max(average.activity$steps)]
```

## Imputing missing values
```{r}
sum(is.na(activity))
activity <- merge(activity, average.activity, by = "interval", suffixes = c("", ".y"))
                              
act <- is.na(activity$steps)
activity$steps[act] <- activity$steps.y[act]
activity <- activity[, c(1:3)]

step.date <- aggregate(steps ~ date, data = activity, FUN = sum)
barplot(step.date$steps, names.arg = step.date$date, xlab = "date", ylab = "steps")
mean(step.date$steps)
median(step.date$steps)
```


## Are there differences in activity patterns between weekdays and weekends?
```{r}
days.analysis <- function(date) {
  if (weekdays(as.Date(date)) %in% c("Saturday", "Sunday")) {
    "weekend"
  } else {
    "weekday"
  }
}
activity$days.analysis <- as.factor(sapply(activity$date, days.analysis))

par(mfrow = c(2, 1))
for (type in c("weekend", "weekday")) {
  steps.type <- aggregate(steps ~ interval, data = activity, subset = activity$days.analysis == 
                            type, FUN = mean)
  plot(steps.type, type = "l", main = type)
}

```

